# Generated by Django 2.2.6 on 2019-11-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del establecimiento', max_length=100)),
                ('cantidad_Habitaciones', models.CharField(help_text='Cantidad de habitaciones disponibles', max_length=4)),
                ('precio_Dia', models.CharField(max_length=8)),
                ('foto', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=6)),
                ('disponibilidad_Inmediata', models.CharField(max_length=2)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Pais')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=50)),
                ('numero', models.IntegerField(default=1)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Pais')),
            ],
        ),
    ]
