# Generated by Django 2.0.7 on 2019-12-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='air_bags',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ano',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='categoria',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cilindrada',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='duenos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='motor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
